### ISSUE TITLE
Botに関係ない開発関連の話ができるサーバーを用意する

### ISSUE THREAD

**Issue by 1ntegrale9** [DiscordBotPortalJP/DiscordBotPortalJP#17]
姉妹鯖として連携し、話が脱線したメンバーを誘導するように

【サーバー名】
Developers Portal（仮）

【コンセプト】
・Bot開発をしたい開発未経験者や、Bot開発以外にも興味を持った開発者向けのコミュニティ
・開発者と開発コミュニティを繋ぎ、成長とモチベーションを支援する

【方針】
・万能なサーバーは目指さない。餅は餅屋。
・常にシンプルで使いやすく。
・メンバーに応じて柔軟に変化する。
・運営コストが大きい施策はやらない。

**Comment by 1ntegrale9** [comment]
とりあえずサーバーを用意 https://discord.gg/grUxj5Njrd

**Comment by sevenc-nanashi** [comment]
閉じてもいい気がする

**Comment by 1ntegrale9** [comment]
作って公開したのでclose
