### ISSUE TITLE
マルチポストの説明文

### ISSUE THREAD

**Issue by sevenc-nanashi** [DiscordBotPortalJP/DiscordBotPortalJP#34]
https://discord.com/channels/494911447420108820/708353429449474098/853239207232405554

これ。

**Comment by 1ntegrale9** [comment]
> マルチポストがマナー的にだめなことを知らない人もいるから、そういうのを教えるテンプレとかあるといいかもね

**Comment by 1ntegrale9** [comment]
一旦これで担保する方向で

https://discord.com/channels/494911447420108820/666146116160585785/820654163435323413

> 他の場所でも同じ質問(マルチポスト)をしている場合は・・・
必ず以下の2点をお守りください。
①「別の場所で質問していること」、「そこで得られた全ての情報」を共有する
②こちらで得られた全ての情報をもう一方に共有する
プログラミング界隈では複数の場所での質問を禁止している場合が多いのでご注意ください。
